#!/usr/bin/env bash
# Live re-validation battery — runs on an authenticated machine (needs /login'd providers).
# Re-confirms every selector used by the profiles via real `gjc -p` calls and records a
# dated evidence table under evidence/. Portable (macOS/Linux), per-call timeout via perl alarm.
#
#   bash scripts/revalidate.sh            # full battery → evidence/<date>-selectors.md
#   SELECTORS_ONLY=1 bash scripts/revalidate.sh   # skip the long-context probes
#
# Exit code: non-zero if any selector EXPECTED to work failed (regression).
set -uo pipefail
cd "$(dirname "$0")/.."
DATE="$(date +%Y-%m-%d)"
OUT="evidence/${DATE}-selectors.md"
mkdir -p evidence
command -v gjc >/dev/null 2>&1 || { echo "gjc not found"; exit 2; }
command -v perl >/dev/null 2>&1 || { echo "perl not found (used for per-call timeout)"; exit 2; }

FAIL=0
{ echo "# Live selector revalidation — ${DATE}"; echo
  echo "Each row: \`gjc -p --no-session --no-tools --model <selector> \"Reply OK\"\`."; echo
  echo "| selector | expect | result |"; echo "| --- | --- | --- |"; } > "$OUT"

# P <selector> <expect: ok|fail>
P(){ local sel="$1" expect="$2" r a
  r="$(perl -e 'alarm 100; exec @ARGV' gjc -p --no-session --no-tools --model "$sel" "Reply with exactly: OK" 2>&1)"
  if printf '%s' "$r" | grep -qw OK; then a="ok"; else
    a="fail[$(printf '%s' "$r" | tr '\n' ' ' | grep -oiE 'not supported|404|500|400|no api key|did not resolve' | head -1)]"; fi
  printf '| `%s` | %s | %s |\n' "$sel" "$expect" "$a" >> "$OUT"
  if [ "$expect" = ok ] && [ "${a#ok}" != "" ] && [ "$a" != ok ]; then
    case "$a" in ok) ;; *) echo "REGRESSION: $sel expected ok, got $a"; FAIL=1;; esac
  fi
}

# --- bundled-catalog selectors used by profiles (must stay ok) ---
for s in \
  "anthropic/claude-opus-4-8:high" "anthropic/claude-sonnet-4-6:high" \
  "openai-codex/gpt-5.5:high" "openai-codex/gpt-5.4:high" \
  "google-antigravity/gemini-3.1-pro-low" "google-antigravity/gemini-3.1-pro-low:high" \
  "xai/grok-4.3:high" "xai/grok-4-1-fast:high" "xai/grok-4-fast:high" \
  "opencode-go/deepseek-v4-flash" "opencode-go/deepseek-v4-pro" ; do P "$s" ok; done

# --- live-catalog (dynamic) selectors: ok once discovery has run ---
for s in "opencode-go/glm-5.2" "google-antigravity/gemini-3.5-flash"; do P "$s" ok-live; done

# --- known rejections (documented; expected to FAIL) ---
for s in "google-antigravity/gemini-3.1-pro-high" "openai-codex/gpt-5.3-codex:high"; do P "$s" fail; done

if [ "${SELECTORS_ONLY:-0}" != 1 ]; then
  { echo; echo "## Single-message @file input limit (separate from the 1M context window)"; echo
    echo "needle answer = ZULU555"; echo
    echo "| selector | @tokens | result |"; echo "| --- | --- | --- |"; } >> "$OUT"
  gen(){ awk -v n="$1" 'BEGIN{b=int(n*0.6);for(i=1;i<=n;i++){if(i==b)printf"Record %06d: PART_X=ZULU555\n",i;else printf"Record %06d: r%d s%d\n",i,i%9,(i*7)%99999}}' > "$2"; }
  T="$(mktemp -d)"; gen 37000 "$T/350k.txt"; gen 50000 "$T/476k.txt"; gen 90000 "$T/857k.txt"
  B(){ local sel="$1" f="$2" lbl="$3" r a
    r="$(perl -e 'alarm 300; exec @ARGV' gjc -p --no-session --no-tools --model "$sel" @"$f" "Output only the PART_X value." 2>&1)"
    if printf '%s' "$r" | grep -q ZULU555; then a="found"; elif [ -z "$r" ]; then a="400/empty"; else a="resp(no-needle)"; fi
    printf '| `%s` | %s | %s |\n' "$sel" "$lbl" "$a" >> "$OUT"; }
  B "anthropic/claude-opus-4-8:high"             "$T/350k.txt" 350k
  B "anthropic/claude-opus-4-8:high"             "$T/476k.txt" 476k
  B "xai/grok-4-fast:high"                       "$T/476k.txt" 476k
  B "xai/grok-4-fast:high"                       "$T/857k.txt" 857k
  rm -rf "$T"
fi

echo >> "$OUT"; echo "_generated by scripts/revalidate.sh on ${DATE}_" >> "$OUT"
echo "Wrote $OUT"; cat "$OUT"
exit $FAIL
